### ISSUE TITLE
Maestro-bot updater script failed to update release/2.1

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1090] opened 2018-04-19 23:41 UTC
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1609398&_a=summary
```
2018-04-19T19:39:09.0680672Z Updating  version variables in E:\A\_work\26\s\build\dependencies.props
2018-04-19T19:39:21.3817970Z ##[error]error: src refspec dotnetbot/UpdateDeps does not match any.
error: failed to push some refs to 'https://@github.com/aspnet/Universe.git'
E:\A\_work\26\s\scripts\UpdateDependencies.ps1 : Cannot bind argument to 
parameter 'Message' because it is null.
At line:1 char:1
+ & "E:\A\_work\26\s\scripts\UpdateDependencies.ps1" -BuildXml https:// ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [UpdateDependencies.ps1], Param 
   eterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,U 
   pdateDependencies.ps1
 
```
cc @ryanbrandenburg

**Comment by ryanbrandenburg** [comment] 2018-04-20 22:48
I sent a PR for this, self-assigning to track until we've confirmed that it works through Maestro.

**Comment by natemcmaster** [comment] 2018-04-24 15:45
New error.
```
remote: Permission to aspnet/Universe.git denied to dotnet-maestro-bot.
Your branch is ahead of 'origin/release/2.1' by 1 commit.
  (use "git push" to publish your local commits)
E:\A\_work\26\s\scripts\UpdateDependencies.ps1 : Cannot bind argument to
Process completed with exit code 0 and had 3 error(s) written to the error stream.
```
Before switching to hub.exe, the way this worked is that dotnet-maestro-bot would push to its fork of Universe, https://github.com/dotnet-maestro-bot/Universe

**Comment by ryanbrandenburg** [comment] 2018-04-24 17:43
Reacting with #1111.

**Comment by ryanbrandenburg** [comment] 2018-04-26 17:28
For sure we should change the name, but it shouldn't matter because it's on different forks, and [the PR was created](https://github.com/aspnet/Universe/pull/1122).

**Comment by natemcmaster** [comment] 2018-04-26 19:01
I think VSTS isn't happy because git.exe is writing to stderr. Also, we should add a check for an existing PR and update that one instead of creating a new PR.
```
 Error creating pull request: Unprocessable Entity (HTTP 422) A pull request already exists for dotnet-maestro-bot:rybrande/UpgradeDepsTest.
```

**Comment by ryanbrandenburg** [comment] 2018-04-26 21:52
We pushed to the same branch that the maestrobot used last time, so we DID update the PR. Do we want to update the text of the message as well?

**Comment by ryanbrandenburg** [comment] 2018-04-26 21:52
Let's double check that we're using Invoke-Block everywhere so Powershell doesn't make us miss failures now that we're ignoring StdErr.

**Comment by ryanbrandenburg** [comment] 2018-04-26 21:55
We're good on Invoke-Blocks, so the only work item left here would be if we wanted to update PR text.

**Comment by ryanbrandenburg** [comment] 2018-04-30 21:59
Closing this since there's no reply. @natemcmaster if you had further comments feel free to re-open.

**Closed** 2018-04-30 22:01 UTC
Labels: 2 - Working, cost: S, task
