### ISSUE TITLE
Setting a machine up to run Universe

### ISSUE THREAD

**Issue by pkapare** [aspnet/Universe#1335] opened 2018-08-24 11:10 UTC
Tried using instructions mentioned ["Setting a machine up to run Universe"](https://github.com/aspnet/Universe/wiki/Setting-a-machine-up-to-run-Universe) to setup machine to run universe. Getting following errors:
…...
……
…...
  - Package: Microsoft.Extensions.Logging.TraceSource Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.Extensions.Logging Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.Extensions.ObjectPool Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.Extensions.Options.ConfigurationExtensions Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.Extensions.Options Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.Extensions.Primitives Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.Extensions.WebEncoders Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.Net.Http.Headers Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.VisualStudio.Web.BrowserLink Version: 3.0.0-alpha1-t006db54bb
   - Package: Microsoft.AspNet.WebApi.Client Version: 5.2.6
  Restoring packages for H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj...
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Antiforgery with version (>= 3.0.0-alpha1-t006db54bb)
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 48 version(s) in myget.dotnetcore [ Nearest version: 2.2.0-preview1-35029 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 46 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 2.2.0-preview1-35029 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 26 version(s) in nuget.org [ Nearest version: 2.2.0-preview1-35029 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 4 version(s) in H:\Github\Universe\artifacts\build\ [ Nearest version: 3.0.0-alpha1-t006db4fdb ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 4 version(s) in https://dotnet.myget.org/F/aspnetcore-master/api/v3/index.json [ Nearest version: 2.0.3 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/roslyn/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://vside.myget.org/F/vsmac/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://vside.myget.org/F/vssdk/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.ApplicationInsights.HostingStartup with version (>= 3.0.0-alpha1-t006db54bb)
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 50 version(s) in myget.dotnetcore [ Nearest version: 2.2.0-preview1-35029 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 48 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 2.2.0-preview1-35029 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 14 version(s) in nuget.org [ Nearest version: 2.2.0-preview1-35029 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 4 version(s) in H:\Github\Universe\artifacts\build\ [ Nearest version: 3.0.0-alpha1-t006db4fdb ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 3 version(s) in https://dotnet.myget.org/F/aspnetcore-master/api/v3/index.json [ Nearest version: 2.0.3 ]
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/roslyn/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://vside.myget.org/F/vsmac/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in https://vside.myget.org/F/vssdk/api/v3/index.json
H:\Github\Universe\.w\pkg\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication.Abstractions with version (>= 3.0.0-alpha1-t006db54bb)
……
……
……
Time Elapsed 00:21:09.45
dotnet.exe failed with exit code: 1
At C:\Users\Vedan\.dotnet\buildtools\korebuild\3.0.0-alpha1-20180821.3\scripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1

**Comment by natemcmaster** [comment] 2018-10-16 22:50
This is a problem we're aware of. As a part of our efforts to merge repos, we're also planning to make it easier for contributors to build the entire ASP.NET Core stack. Closing as a duplicate of #512

**Closed by natemcmaster** 2018-10-16 22:50 UTC
