### ISSUE TITLE
K ignores dnvmUse on Mono

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#279] opened 2015-09-16 17:26 UTC
Related to https://github.com/aspnet/Universe/issues/272

Using `K(cmd,path,dnvmUse)` in a makefile.shade does not work as `K` ignores dnvmUse completely when running on Mono

**Comment by dougbu** [comment] 2015-09-16 18:31
@natemcmaster I was planning on addressing this bit as part of doing #272 (soon). Are you separating this out because you can't wait? If not, is this a dupe of @272?

**Comment by natemcmaster** [comment] 2015-09-16 18:33
@dougbu Yes, separating out because this is a bug. It took me a few weeks to realize [this command](https://github.com/aspnet/Microsoft.Data.Sqlite/commit/222ece84f318662dbfc35c593689de718deebf9e) is not actually running CoreCLR. It silently ignores the dnvmUse parameter.

**Comment by dougbu** [comment] 2015-10-17 21:27
This has been working fine since 618a73b

**Closed by dougbu** 2015-10-17 21:27 UTC
