### ISSUE TITLE
Signing failure in UnzipArchive: The file '......\Microsoft.AspNetCore.ApplicationInsights.HostingStartup.pdb' already exists

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#951] opened 2018-03-12 15:56 UTC
```
[01:16:56] Extracted 11 file(s) to 'C:\b\w\62a23bcc6cf496bf\obj\UnsignedSymbolsPackages\RazorPageGenerator.2.1.0-preview2-30292.symbols'
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: The "UnzipArchive" task failed unexpectedly. [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: System.IO.IOException: The file 'C:\b\w\62a23bcc6cf496bf\obj\UnsignedSymbolsPackages\runtime.linux-x64.Microsoft.AspNetCore.All.2.1.0-preview2-30292.symbols\runtimes\linux-x64\lib\netcoreapp2.1\Microsoft.AspNetCore.ApplicationInsights.HostingStartup.pdb' already exists. [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite) [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: at Microsoft.AspNetCore.BuildTools.UnzipArchive.Execute() in C:\b\w\9571b3e5f03d051f\modules\BuildTools.Tasks\UnzipArchive.cs:line 56 [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in E:\A\_work\62\s\src\Build\BackEnd\TaskExecutionHost\TaskExecutionHost.cs:line 631 [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
[01:16:58]C:\b\w\62a23bcc6cf496bf\build\Prepare.targets(35,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in E:\A\_work\62\s\src\Build\BackEnd\Components\RequestBuilder\TaskBuilder.cs:line 787 [C:\b\w\62a23bcc6cf496bf\.dotnet\buildtools\korebuild\2.1.0-preview2-15696\KoreBuild.proj]
```

/cc @natemcmaster  @ryanbrandenburg

**Comment by pakrym** [comment] 2018-03-12 15:56
http://aspnetci/viewLog.html?buildId=419083&buildTypeId=CoherenceSigned&tab=buildLog

**Comment by Eilon** [comment] 2018-03-12 16:14
@ryanbrandenburg can you take a look or redirect as appropriate?

**Comment by ryanbrandenburg** [comment] 2018-03-12 17:28
It looks like 2 copies of files are making their way into the symbols nupkgs for `runtime.linux-x64.Microsoft.AspNetCore.All` I'm trying to figure out why that might be right now.

**Comment by ryanbrandenburg** [comment] 2018-03-12 17:43
We believe this is caused by the new CLI. John is reverting it now and will then investigate further when it's not breaking the build, so I'm assigning this to him for now.

**Closed** 2018-03-12 23:15 UTC
Labels: 3 - Done, task
