### ISSUE TITLE
 Could not find an installation of Visual Studio that satisifies the specified requirements in korebuild.json.

### ISSUE THREAD

**Issue by pkapare** [aspnet/Universe#912] opened 2018-02-21 10:41 UTC
I am getting following error while trying to build Universe repository. 

**My System Configuration :** 
OS : Windows 10 Pro, Version : 1709, OS Build : 16299.248
1. Visual Studio 2017 Community
2. Visual Studio 2017 Community Preview
3. All workloads for both VS installed.
4. Windows 10 SDK and Windows 8.1 SDK installed.

When I run build.cmd, I am getting following error:

H:\Github\DotNetCore\Universe\modules\IISIntegration>build.cmd
Using KoreBuild 2.1.0-preview2-15707
WARNING: dotnet found on the system PATH is 'C:\Program Files\dotnet\dotnet.exe' but KoreBuild will use 'C:\Users\Vedan\.dotnet\x64\dotnet.exe'.
WARNING: Adding 'C:\Users\Vedan\.dotnet\x64' to system PATH permanently may be required for applications like Visual Studio or VS Code to work correctly.
Adding C:\Users\Vedan\.dotnet\x64 to PATH
.NET Core runtime 2.0.5 is already installed. Skipping installation.
.NET Core SDK 2.1.300-preview2-008173 is already installed. Skipping installation.
>>> dotnet.exe msbuild @H:\Github\DotNetCore\Universe\modules\IISIntegration\artifacts\logs\msbuild.rsp @H:\Github\DotNetCore\Universe\modules\IISIntegration\artifacts\logs\msbuild.logger.rsp
C:\Users\Vedan\.dotnet\buildtools\korebuild\2.1.0-preview2-15707\modules\KoreBuild.Tasks\module.targets(143,5): error : Could not find an installation of Visual Studio that satisifies the specified requirements in H:\Github\DotNetCore\Universe\modules\IISIntegration/korebuild.json. See https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community for more details on any missing components. [C:\Users\Vedan\.dotnet\buildtools\korebuild\2.1.0-preview2-15707\KoreBuild.proj]

Build FAILED.

C:\Users\Vedan\.dotnet\buildtools\korebuild\2.1.0-preview2-15707\modules\KoreBuild.Tasks\module.targets(143,5): error : Could not find an installation of Visual Studio that satisifies the specified requirements in H:\Github\DotNetCore\Universe\modules\IISIntegration/korebuild.json. See https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community for more details on any missing components. [C:\Users\Vedan\.dotnet\buildtools\korebuild\2.1.0-preview2-15707\KoreBuild.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.38
dotnet.exe failed with exit code: 1
At C:\Users\Vedan\.dotnet\buildtools\korebuild\2.1.0-preview2-15707\scripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1

When I modify Korebuild.json present in Universe directory and remove "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81" from requiredworkloads build works perfectly fine. My question is even when I have both Windows 10 and 8.1 SDKs installed why its not detecting it. Also do we need to check this requirement on Windows 10 machine?

**Comment by natemcmaster** [comment] 2018-03-01 22:02
When you install VS, you need to make sure you also have this box checked:

<img width="346" alt="untitled" src="https://user-images.githubusercontent.com/2696087/36872104-fa33441a-1d58-11e8-8b76-e20a6e10745d.png">

You need the UCRT SDK in addition to the Windows 10 and 8.1 SDKs.

Closing as a duplicate of #903. We plan to write a script that would make it easier to install required workloads.

**Closed by natemcmaster** 2018-03-01 22:02 UTC
